import * as THREE from 'three';
import { GLTFExporter } from 'three/addons/exporters/GLTFExporter.js';
import { OBJExporter } from 'three/addons/exporters/OBJExporter.js';
import type { SceneManager } from './SceneManager';

export type ExportFormat = 'glb' | 'fbx' | 'obj';

function triggerDownload(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function buildExportGroup(sceneManager: SceneManager): THREE.Group {
  const group = new THREE.Group();
  const allClips: THREE.AnimationClip[] = [];

  for (const [id, obj] of sceneManager.meshMap) {
    group.add(obj.clone());
    allClips.push(...sceneManager.animationManager.getAllClips(id));
  }

  group.animations = allClips;
  return group;
}

async function exportGLB(sceneManager: SceneManager): Promise<void> {
  const group = buildExportGroup(sceneManager);
  const exporter = new GLTFExporter();

  const buffer: ArrayBuffer = await new Promise((resolve, reject) => {
    exporter.parse(
      group,
      (result) => resolve(result as ArrayBuffer),
      reject,
      { binary: true, animations: group.animations },
    );
  });

  triggerDownload(new Blob([buffer], { type: 'application/octet-stream' }), 'scene.glb');
}

function exportOBJ(sceneManager: SceneManager): void {
  const group = buildExportGroup(sceneManager);
  const exporter = new OBJExporter();
  const content = exporter.parse(group);
  triggerDownload(new Blob([content], { type: 'text/plain' }), 'scene.obj');
}

function buildFBXAscii(sceneManager: SceneManager): string {
  const lines: string[] = [];
  let idCounter = 100000;
  let meshIndex = 0;

  lines.push('; FBX 7.4.0 project file');
  lines.push('; Generated by HackCanada2026');
  lines.push('');
  lines.push('FBXHeaderExtension:  {');
  lines.push('\tFBXHeaderVersion: 1003');
  lines.push('\tFBXVersion: 7400');
  lines.push('\tCreator: "HackCanada2026"');
  lines.push('}');
  lines.push('');
  lines.push('GlobalSettings:  {');
  lines.push('\tVersion: 1000');
  lines.push('\tProperties70:  {');
  lines.push('\t\tP: "UpAxis", "int", "Integer", "",1');
  lines.push('\t\tP: "UpAxisSign", "int", "Integer", "",1');
  lines.push('\t\tP: "FrontAxis", "int", "Integer", "",2');
  lines.push('\t\tP: "FrontAxisSign", "int", "Integer", "",1');
  lines.push('\t\tP: "CoordAxis", "int", "Integer", "",0');
  lines.push('\t\tP: "CoordAxisSign", "int", "Integer", "",1');
  lines.push('\t\tP: "UnitScaleFactor", "double", "Number", "",1');
  lines.push('\t}');
  lines.push('}');
  lines.push('');

  const objectLines: string[] = ['Objects:  {'];
  const connectionLines: string[] = ['Connections:  {'];

  for (const [, obj] of sceneManager.meshMap) {
    const meshes: THREE.Mesh[] = [];
    if ((obj as THREE.Mesh).isMesh) {
      meshes.push(obj as THREE.Mesh);
    } else {
      obj.traverse((child) => {
        if ((child as THREE.Mesh).isMesh) {
          meshes.push(child as THREE.Mesh);
        }
      });
    }

    for (const mesh of meshes) {
      const geomId = idCounter++;
      const modelId = idCounter++;
      const name = `Object_${meshIndex++}`;

      const geo = mesh.geometry.toNonIndexed();
      if (!geo.getAttribute('normal')) geo.computeVertexNormals();

      const posAttr = geo.getAttribute('position') as THREE.BufferAttribute;
      const normAttr = geo.getAttribute('normal') as THREE.BufferAttribute | undefined;
      const uvAttr = geo.getAttribute('uv') as THREE.BufferAttribute | undefined;
      const count = posAttr.count;

      const vertices: number[] = [];
      for (let i = 0; i < count; i++) {
        vertices.push(posAttr.getX(i), posAttr.getY(i), posAttr.getZ(i));
      }

      // FBX polygon indices: last index of each polygon is -(index + 1)
      const polygons: number[] = [];
      for (let i = 0; i < count; i += 3) {
        polygons.push(i, i + 1, -(i + 3));
      }

      objectLines.push(`\tGeometry: ${geomId}, "Geometry::${name}", "Mesh" {`);
      objectLines.push(`\t\tGeometryVersion: 124`);
      objectLines.push(`\t\tVertices: *${vertices.length} {`);
      objectLines.push(`\t\t\ta: ${vertices.join(',')}`);
      objectLines.push(`\t\t}`);
      objectLines.push(`\t\tPolygonVertexIndex: *${polygons.length} {`);
      objectLines.push(`\t\t\ta: ${polygons.join(',')}`);
      objectLines.push(`\t\t}`);

      if (normAttr) {
        const normals: number[] = [];
        for (let i = 0; i < count; i++) {
          normals.push(normAttr.getX(i), normAttr.getY(i), normAttr.getZ(i));
        }
        objectLines.push(`\t\tLayerElementNormal: 0 {`);
        objectLines.push(`\t\t\tVersion: 101`);
        objectLines.push(`\t\t\tName: ""`);
        objectLines.push(`\t\t\tMappingInformationType: "ByPolygonVertex"`);
        objectLines.push(`\t\t\tReferenceInformationType: "Direct"`);
        objectLines.push(`\t\t\tNormals: *${normals.length} {`);
        objectLines.push(`\t\t\t\ta: ${normals.join(',')}`);
        objectLines.push(`\t\t\t}`);
        objectLines.push(`\t\t}`);
      }

      if (uvAttr) {
        const uvs: number[] = [];
        for (let i = 0; i < count; i++) {
          uvs.push(uvAttr.getX(i), uvAttr.getY(i));
        }
        const uvIndices = Array.from({ length: count }, (_, i) => i);
        objectLines.push(`\t\tLayerElementUV: 0 {`);
        objectLines.push(`\t\t\tVersion: 101`);
        objectLines.push(`\t\t\tName: "UVMap"`);
        objectLines.push(`\t\t\tMappingInformationType: "ByPolygonVertex"`);
        objectLines.push(`\t\t\tReferenceInformationType: "IndexToDirect"`);
        objectLines.push(`\t\t\tUV: *${uvs.length} {`);
        objectLines.push(`\t\t\t\ta: ${uvs.join(',')}`);
        objectLines.push(`\t\t\t}`);
        objectLines.push(`\t\t\tUVIndex: *${uvIndices.length} {`);
        objectLines.push(`\t\t\t\ta: ${uvIndices.join(',')}`);
        objectLines.push(`\t\t\t}`);
        objectLines.push(`\t\t}`);
      }

      objectLines.push(`\t\tLayer: 0 {`);
      objectLines.push(`\t\t\tVersion: 100`);
      if (normAttr) {
        objectLines.push(`\t\t\tLayerElement:  {`);
        objectLines.push(`\t\t\t\tType: "LayerElementNormal"`);
        objectLines.push(`\t\t\t\tTypedIndex: 0`);
        objectLines.push(`\t\t\t}`);
      }
      if (uvAttr) {
        objectLines.push(`\t\t\tLayerElement:  {`);
        objectLines.push(`\t\t\t\tType: "LayerElementUV"`);
        objectLines.push(`\t\t\t\tTypedIndex: 0`);
        objectLines.push(`\t\t\t}`);
      }
      objectLines.push(`\t\t}`);
      objectLines.push(`\t}`);
      objectLines.push('');

      // Decompose world transform for the Model node
      mesh.updateWorldMatrix(true, false);
      const pos = new THREE.Vector3();
      const quat = new THREE.Quaternion();
      const scl = new THREE.Vector3();
      mesh.matrixWorld.decompose(pos, quat, scl);
      const euler = new THREE.Euler().setFromQuaternion(quat, 'ZYX');
      const rx = THREE.MathUtils.radToDeg(euler.x);
      const ry = THREE.MathUtils.radToDeg(euler.y);
      const rz = THREE.MathUtils.radToDeg(euler.z);

      objectLines.push(`\tModel: ${modelId}, "Model::${name}", "Mesh" {`);
      objectLines.push(`\t\tVersion: 232`);
      objectLines.push(`\t\tProperties70:  {`);
      objectLines.push(`\t\t\tP: "RotationActive", "bool", "", "",1`);
      objectLines.push(`\t\t\tP: "InheritType", "enum", "", "",1`);
      objectLines.push(`\t\t\tP: "ScalingMax", "Vector3D", "Vector", "",0,0,0`);
      objectLines.push(`\t\t\tP: "DefaultAttributeIndex", "int", "Integer", "",0`);
      objectLines.push(`\t\t\tP: "Lcl Translation", "Lcl Translation", "", "A",${pos.x},${pos.y},${pos.z}`);
      objectLines.push(`\t\t\tP: "Lcl Rotation", "Lcl Rotation", "", "A",${rx},${ry},${rz}`);
      objectLines.push(`\t\t\tP: "Lcl Scaling", "Lcl Scaling", "", "A",${scl.x},${scl.y},${scl.z}`);
      objectLines.push(`\t\t}`);
      objectLines.push(`\t\tShading: T`);
      objectLines.push(`\t\tCulling: "CullingOff"`);
      objectLines.push(`\t}`);
      objectLines.push('');

      connectionLines.push(`\tC: "OO",${geomId},${modelId}`);
      connectionLines.push(`\tC: "OO",${modelId},0`);
    }
  }

  objectLines.push('}');
  connectionLines.push('}');

  lines.push(...objectLines);
  lines.push('');
  lines.push(...connectionLines);

  return lines.join('\n');
}

function exportFBX(sceneManager: SceneManager): void {
  const content = buildFBXAscii(sceneManager);
  triggerDownload(new Blob([content], { type: 'application/octet-stream' }), 'scene.fbx');
}

export async function exportObjectById(
  sceneManager: SceneManager,
  objectId: string,
  objectName: string,
  format: ExportFormat,
): Promise<void> {
  const obj = sceneManager.getMeshById(objectId);
  if (!obj) return;

  const safeName = objectName.replace(/[^a-zA-Z0-9_-]/g, '_') || objectId;
  const clips = sceneManager.animationManager.getAllClips(objectId);

  if (format === 'glb') {
    const exporter = new GLTFExporter();
    const buffer: ArrayBuffer = await new Promise((resolve, reject) => {
      exporter.parse(
        obj,
        (result) => resolve(result as ArrayBuffer),
        reject,
        { binary: true, animations: clips },
      );
    });
    triggerDownload(new Blob([buffer], { type: 'application/octet-stream' }), `${safeName}.glb`);
    return;
  }

  if (format === 'obj') {
    const exporter = new OBJExporter();
    const content = exporter.parse(obj);
    triggerDownload(new Blob([content], { type: 'text/plain' }), `${safeName}.obj`);
    return;
  }

  if (format === 'fbx') {
    const meshes: THREE.Mesh[] = [];
    if ((obj as THREE.Mesh).isMesh) {
      meshes.push(obj as THREE.Mesh);
    } else {
      obj.traverse((child) => {
        if ((child as THREE.Mesh).isMesh) meshes.push(child as THREE.Mesh);
      });
    }

    const lines: string[] = [];
    let idCounter = 100000;
    let meshIndex = 0;

    lines.push('; FBX 7.4.0 project file');
    lines.push('; Generated by HackCanada2026');
    lines.push('');
    lines.push('FBXHeaderExtension:  {');
    lines.push('\tFBXHeaderVersion: 1003');
    lines.push('\tFBXVersion: 7400');
    lines.push('\tCreator: "HackCanada2026"');
    lines.push('}');
    lines.push('');
    lines.push('GlobalSettings:  {');
    lines.push('\tVersion: 1000');
    lines.push('\tProperties70:  {');
    lines.push('\t\tP: "UpAxis", "int", "Integer", "",1');
    lines.push('\t\tP: "UpAxisSign", "int", "Integer", "",1');
    lines.push('\t\tP: "FrontAxis", "int", "Integer", "",2');
    lines.push('\t\tP: "FrontAxisSign", "int", "Integer", "",1');
    lines.push('\t\tP: "CoordAxis", "int", "Integer", "",0');
    lines.push('\t\tP: "CoordAxisSign", "int", "Integer", "",1');
    lines.push('\t\tP: "UnitScaleFactor", "double", "Number", "",1');
    lines.push('\t}');
    lines.push('}');
    lines.push('');

    const objectLines: string[] = ['Objects:  {'];
    const connectionLines: string[] = ['Connections:  {'];

    for (const mesh of meshes) {
      const geomId = idCounter++;
      const modelId = idCounter++;
      const name = `${safeName}_${meshIndex++}`;

      const geo = mesh.geometry.toNonIndexed();
      if (!geo.getAttribute('normal')) geo.computeVertexNormals();

      const posAttr = geo.getAttribute('position') as THREE.BufferAttribute;
      const normAttr = geo.getAttribute('normal') as THREE.BufferAttribute | undefined;
      const uvAttr = geo.getAttribute('uv') as THREE.BufferAttribute | undefined;
      const count = posAttr.count;

      const vertices: number[] = [];
      for (let i = 0; i < count; i++) {
        vertices.push(posAttr.getX(i), posAttr.getY(i), posAttr.getZ(i));
      }
      const polygons: number[] = [];
      for (let i = 0; i < count; i += 3) {
        polygons.push(i, i + 1, -(i + 3));
      }

      objectLines.push(`\tGeometry: ${geomId}, "Geometry::${name}", "Mesh" {`);
      objectLines.push(`\t\tGeometryVersion: 124`);
      objectLines.push(`\t\tVertices: *${vertices.length} {`);
      objectLines.push(`\t\t\ta: ${vertices.join(',')}`);
      objectLines.push(`\t\t}`);
      objectLines.push(`\t\tPolygonVertexIndex: *${polygons.length} {`);
      objectLines.push(`\t\t\ta: ${polygons.join(',')}`);
      objectLines.push(`\t\t}`);

      if (normAttr) {
        const normals: number[] = [];
        for (let i = 0; i < count; i++) {
          normals.push(normAttr.getX(i), normAttr.getY(i), normAttr.getZ(i));
        }
        objectLines.push(`\t\tLayerElementNormal: 0 {`);
        objectLines.push(`\t\t\tVersion: 101`);
        objectLines.push(`\t\t\tName: ""`);
        objectLines.push(`\t\t\tMappingInformationType: "ByPolygonVertex"`);
        objectLines.push(`\t\t\tReferenceInformationType: "Direct"`);
        objectLines.push(`\t\t\tNormals: *${normals.length} {`);
        objectLines.push(`\t\t\t\ta: ${normals.join(',')}`);
        objectLines.push(`\t\t\t}`);
        objectLines.push(`\t\t}`);
      }

      if (uvAttr) {
        const uvs: number[] = [];
        for (let i = 0; i < count; i++) {
          uvs.push(uvAttr.getX(i), uvAttr.getY(i));
        }
        const uvIndices = Array.from({ length: count }, (_, i) => i);
        objectLines.push(`\t\tLayerElementUV: 0 {`);
        objectLines.push(`\t\t\tVersion: 101`);
        objectLines.push(`\t\t\tName: "UVMap"`);
        objectLines.push(`\t\t\tMappingInformationType: "ByPolygonVertex"`);
        objectLines.push(`\t\t\tReferenceInformationType: "IndexToDirect"`);
        objectLines.push(`\t\t\tUV: *${uvs.length} {`);
        objectLines.push(`\t\t\t\ta: ${uvs.join(',')}`);
        objectLines.push(`\t\t\t}`);
        objectLines.push(`\t\t\tUVIndex: *${uvIndices.length} {`);
        objectLines.push(`\t\t\t\ta: ${uvIndices.join(',')}`);
        objectLines.push(`\t\t\t}`);
        objectLines.push(`\t\t}`);
      }

      objectLines.push(`\t\tLayer: 0 {`);
      objectLines.push(`\t\t\tVersion: 100`);
      if (normAttr) {
        objectLines.push(`\t\t\tLayerElement:  {`);
        objectLines.push(`\t\t\t\tType: "LayerElementNormal"`);
        objectLines.push(`\t\t\t\tTypedIndex: 0`);
        objectLines.push(`\t\t\t}`);
      }
      if (uvAttr) {
        objectLines.push(`\t\t\tLayerElement:  {`);
        objectLines.push(`\t\t\t\tType: "LayerElementUV"`);
        objectLines.push(`\t\t\t\tTypedIndex: 0`);
        objectLines.push(`\t\t\t}`);
      }
      objectLines.push(`\t\t}`);
      objectLines.push(`\t}`);
      objectLines.push('');

      mesh.updateWorldMatrix(true, false);
      const pos = new THREE.Vector3();
      const quat = new THREE.Quaternion();
      const scl = new THREE.Vector3();
      mesh.matrixWorld.decompose(pos, quat, scl);
      const euler = new THREE.Euler().setFromQuaternion(quat, 'ZYX');

      objectLines.push(`\tModel: ${modelId}, "Model::${name}", "Mesh" {`);
      objectLines.push(`\t\tVersion: 232`);
      objectLines.push(`\t\tProperties70:  {`);
      objectLines.push(`\t\t\tP: "RotationActive", "bool", "", "",1`);
      objectLines.push(`\t\t\tP: "InheritType", "enum", "", "",1`);
      objectLines.push(`\t\t\tP: "ScalingMax", "Vector3D", "Vector", "",0,0,0`);
      objectLines.push(`\t\t\tP: "DefaultAttributeIndex", "int", "Integer", "",0`);
      objectLines.push(`\t\t\tP: "Lcl Translation", "Lcl Translation", "", "A",${pos.x},${pos.y},${pos.z}`);
      objectLines.push(`\t\t\tP: "Lcl Rotation", "Lcl Rotation", "", "A",${THREE.MathUtils.radToDeg(euler.x)},${THREE.MathUtils.radToDeg(euler.y)},${THREE.MathUtils.radToDeg(euler.z)}`);
      objectLines.push(`\t\t\tP: "Lcl Scaling", "Lcl Scaling", "", "A",${scl.x},${scl.y},${scl.z}`);
      objectLines.push(`\t\t}`);
      objectLines.push(`\t\tShading: T`);
      objectLines.push(`\t\tCulling: "CullingOff"`);
      objectLines.push(`\t}`);
      objectLines.push('');

      connectionLines.push(`\tC: "OO",${geomId},${modelId}`);
      connectionLines.push(`\tC: "OO",${modelId},0`);
    }

    objectLines.push('}');
    connectionLines.push('}');
    lines.push(...objectLines, '', ...connectionLines);
    triggerDownload(new Blob([lines.join('\n')], { type: 'application/octet-stream' }), `${safeName}.fbx`);
  }
}

export async function exportScene(
  sceneManager: SceneManager,
  format: ExportFormat,
): Promise<void> {
  switch (format) {
    case 'glb':
      await exportGLB(sceneManager);
      break;
    case 'obj':
      exportOBJ(sceneManager);
      break;
    case 'fbx':
      exportFBX(sceneManager);
      break;
  }
}
